import {
  Activity,
  AlarmClock,
  AlertTriangle,
  BatteryMedium,
  Bell,
  Clock3,
  Droplets,
  Gauge,
  Hash,
  ImageIcon,
  Info,
  Lightbulb,
  ListFilter,
  Minus,
  MonitorDot,
  MousePointerClick,
  Move,
  Palette,
  PieChart,
  Rows3,
  Signal,
  SlidersHorizontal,
  SquareStack,
  Thermometer,
  TimerReset,
  ToggleLeft,
  Type,
  Waves,
  Wifi,
} from "lucide-react";
import type { WidgetDefinition, WidgetEditorField } from "../types";
import {
  ChartWidgetRenderer,
  ControlWidgetRenderer,
  DisplayWidgetRenderer,
  StatusWidgetRenderer,
  UtilityWidgetRenderer,
} from "../components/renderers/WidgetRenderer";

const layoutFields: WidgetEditorField[] = [
  { key: "width", label: "Width", kind: "number", scope: "layout", section: "Layout", min: 1, max: 3, step: 1 },
  { key: "height", label: "Height", kind: "number", scope: "layout", section: "Layout", min: 1, max: 3, step: 1 },
];

const numericFields: WidgetEditorField[] = [
  {
    key: "min",
    label: "Min",
    kind: "number",
    scope: "config",
    section: "Numeric",
    step: 0.1,
    visible: (draft) => draft.binding?.binding_type !== "virtual" || !draft.binding?.datastream_id,
  },
  {
    key: "max",
    label: "Max",
    kind: "number",
    scope: "config",
    section: "Numeric",
    step: 0.1,
    visible: (draft) => draft.binding?.binding_type !== "virtual" || !draft.binding?.datastream_id,
  },
  {
    key: "step",
    label: "Step",
    kind: "number",
    scope: "config",
    section: "Numeric",
    step: 0.1,
    visible: (draft) => draft.binding?.binding_type !== "virtual" || !draft.binding?.datastream_id,
  },
  { key: "unit", label: "Unit", kind: "text", scope: "config", section: "Display", placeholder: "°C" },
  { key: "decimalPlaces", label: "Decimal places", kind: "number", scope: "config", section: "Display", min: 0, max: 6, step: 1 },
];

const displayFields: WidgetEditorField[] = [
  { key: "prefix", label: "Prefix", kind: "text", scope: "config", section: "Display", placeholder: "~" },
  { key: "suffix", label: "Suffix", kind: "text", scope: "config", section: "Display", placeholder: "/100" },
  { key: "color", label: "Accent color", kind: "color", scope: "config", section: "Display", visible: (draft) => draft.widget_type !== "multi_telemetry_chart" },
  { key: "hideTitle", label: "Hide widget title", kind: "boolean", scope: "config", section: "Display", description: "Hide the widget title in the dashboard header." },
];

const thresholdFields: WidgetEditorField[] = [
  {
    key: "thresholdCondition",
    label: "Trigger condition",
    kind: "select",
    scope: "config",
    section: "Thresholds",
    options: [
      { label: "Value is above (>=) thresholds", value: "above" },
      { label: "Value is below (<=) thresholds", value: "below" },
    ],
  },
  { key: "warningThreshold", label: "Warning threshold", kind: "number", scope: "config", section: "Thresholds", step: 0.1 },
  { key: "dangerThreshold", label: "Danger threshold", kind: "number", scope: "config", section: "Thresholds", step: 0.1 },
];

const chartFields: WidgetEditorField[] = [
  {
    key: "chartType",
    label: "Chart type",
    kind: "select",
    scope: "config",
    section: "Style",
    options: [
      { label: "Line", value: "line" },
      { label: "Area", value: "area" },
      { label: "Bar", value: "bar" },
    ],
  },
  {
    key: "curveType",
    label: "Line shape",
    kind: "select",
    scope: "config",
    section: "Style",
    options: [
      { label: "Smooth", value: "monotone" },
      { label: "Straight", value: "linear" },
      { label: "Step", value: "step" },
    ],
    visible: (draft) => String(draft.config.chartType ?? draft.config.chart_type ?? "line") !== "bar",
  },
  {
    key: "timeRange",
    label: "Time range",
    kind: "select",
    scope: "config",
    section: "Data",
    options: [
      { label: "Live (15 minutes)", value: "live" },
      { label: "6 hours", value: "6h" },
      { label: "1 day", value: "1d" },
      { label: "1 week", value: "1w" },
      { label: "30 days", value: "1m" },
    ],
  },
  { key: "refreshIntervalSeconds", label: "Refresh interval (s)", kind: "number", scope: "config", section: "Data", min: 5, max: 300, step: 5, description: "How often the widget requests new telemetry." },
  {
    key: "aggregation",
    label: "Aggregation",
    kind: "select",
    scope: "config",
    section: "Data",
    options: [
      { label: "Average", value: "avg" },
      { label: "Min", value: "min" },
      { label: "Max", value: "max" },
    ],
  },
  {
    key: "maxDataPoints",
    label: "Max data points",
    kind: "number",
    scope: "config",
    section: "Data",
    min: 10,
    max: 500,
    step: 10,
    description: "Controls the maximum number of plotted points.",
  },
  { key: "min", label: "Y-axis minimum", labelKey: "projects:editor.ui.field.yAxisMin", kind: "number", scope: "config", section: "Scale", step: 0.1, description: "Leave empty to calculate automatically.", descriptionKey: "projects:editor.ui.field_desc.yAxisMin" },
  { key: "max", label: "Y-axis maximum", labelKey: "projects:editor.ui.field.yAxisMax", kind: "number", scope: "config", section: "Scale", step: 0.1, description: "Leave empty to calculate automatically.", descriptionKey: "projects:editor.ui.field_desc.yAxisMax" },
  { key: "unit", label: "Value unit", labelKey: "projects:editor.ui.field.valueUnit", kind: "text", scope: "config", section: "Scale", placeholder: "°C, %, V" },
  { key: "decimalPlaces", label: "Decimal places", kind: "number", scope: "config", section: "Scale", min: 0, max: 6, step: 1 },
  { key: "showGrid", label: "Show grid", kind: "boolean", scope: "config", section: "Display", description: "Display horizontal guide lines behind the chart." },
  { key: "showXAxis", label: "Show X axis", kind: "boolean", scope: "config", section: "Display", description: "Display time labels along the bottom axis." },
  { key: "showYAxis", label: "Show Y axis", kind: "boolean", scope: "config", section: "Display", description: "Display numeric values along the left axis." },
  { key: "showLegend", label: "Show legend", kind: "boolean", scope: "config", section: "Display", visible: (draft) => draft.widget_type === "multi_telemetry_chart", description: "Display the channel names below the chart." },
  {
    key: "connectNulls",
    label: "Connect missing values",
    kind: "boolean",
    scope: "config",
    section: "Display",
    description: "Continue the line across empty telemetry buckets.",
    visible: (draft) => String(draft.config.chartType ?? draft.config.chart_type ?? "line") !== "bar",
  },
];

const controlFields: WidgetEditorField[] = [
  { key: "confirmBeforeSend", label: "Confirm before send", kind: "boolean", scope: "config", section: "Behavior", description: "Ask for confirmation before sending commands." },
  { key: "allowOfflineControl", label: "Allow offline control", kind: "boolean", scope: "config", section: "Behavior", description: "Keep the control active even when the device looks offline." },
];

const pulseFields: WidgetEditorField[] = [
  { key: "pulseDurationMs", label: "Pulse duration (ms)", kind: "number", scope: "config", section: "Behavior", min: 100, max: 10000, step: 100 },
];

const toggleLabelFields: WidgetEditorField[] = [
  { key: "showStateLabels", label: "Show on/off labels", kind: "boolean", scope: "config", section: "Display", description: "Show the current state label next to the switch." },
  { key: "onLabel", label: "ON label", kind: "text", scope: "config", section: "Display", placeholder: "ON", visible: (draft) => draft.config.showStateLabels === true },
  { key: "offLabel", label: "OFF label", kind: "text", scope: "config", section: "Display", placeholder: "OFF", visible: (draft) => draft.config.showStateLabels === true },
  {
    key: "labelPosition",
    label: "Label position",
    kind: "select",
    scope: "config",
    section: "Display",
    visible: (draft) => draft.config.showStateLabels === true,
    options: [
      { label: "Left", value: "left" },
      { label: "Right", value: "right" },
    ],
  },
];

const optionFields: WidgetEditorField[] = [
  {
    key: "optionsCsv",
    label: "Danh sách chế độ",
    kind: "textarea",
    scope: "config",
    section: "Behavior",
    placeholder: "Tự động=auto\nThủ công=manual\nBảo trì=maintenance",
    placeholderKey: "projects:editor.ui.placeholder.optionsCsv",
    description: "Nhập mỗi chế độ trên một dòng theo dạng Tên hiển thị=Giá trị gửi. Có thể nhập value đơn hoặc phân tách bằng dấu phẩy.",
    visible: (draft) => draft.binding?.binding_type !== "virtual" || !draft.binding?.datastream_id,
  },
];

const textFields: WidgetEditorField[] = [
  { key: "text", label: "Text", kind: "textarea", scope: "config", section: "Content", placeholder: "Display note or label", placeholderKey: "projects:editor.ui.placeholder.text" },
];

const markdownFields: WidgetEditorField[] = [
  { key: "markdown", label: "Markdown", kind: "textarea", scope: "config", section: "Content", placeholder: "## Note", placeholderKey: "projects:editor.ui.placeholder.markdown" },
];

const imageFields: WidgetEditorField[] = [
  { key: "imageUrl", label: "Image URL", kind: "text", scope: "config", section: "Content", placeholder: "https://example.com/panel.png" },
];

function makeDefinition(definition: WidgetDefinition): WidgetDefinition {
  const id = definition.id;
  const numericControls = new Set(["slider_control", "knob_dial_control", "numeric_input", "stepper_control"]);
  const booleanControls = new Set(["toggle_switch", "push_button", "momentary_button", "schedule_button_timer"]);
  const optionControls = new Set(["dropdown_command_selector", "segmented_control"]);
  const booleanTelemetry = new Set(["led_indicator", "icon_status", "device_online_status", "boolean_status_card", "alarm_badge"]);
  const numericTelemetry = new Set([
    "number_card",
    "battery_indicator",
    "signal_strength_wifi_rssi",
    "progress_bar",
    "thermometer",
    "humidity_card",
    "circular_gauge",
    "linear_gauge",
    "multi_value_card",
    "gauge_widget",
    "threshold_alert_card",
    "ota_job_status",
  ]);

  let datastream = definition.datastream;
  if (!datastream && id === "multi_telemetry_chart") {
    datastream = { dataTypes: ["integer", "double"], directions: ["telemetry", "bidirectional"], virtualOnly: true };
  } else if (!datastream && numericControls.has(id)) {
    datastream = { dataTypes: ["integer", "double"], directions: ["command", "bidirectional"], virtualOnly: true };
  } else if (!datastream && booleanControls.has(id)) {
    datastream = { dataTypes: ["boolean"], directions: ["command", "bidirectional"] };
  } else if (!datastream && optionControls.has(id)) {
    datastream = { dataTypes: ["boolean", "integer", "double", "string"], directions: ["command", "bidirectional"], virtualOnly: true };
  } else if (!datastream && definition.category === "chart") {
    datastream = { dataTypes: ["integer", "double"], directions: ["telemetry", "bidirectional"] };
  } else if (!datastream && numericTelemetry.has(id)) {
    datastream = { dataTypes: ["integer", "double"], directions: ["telemetry", "bidirectional"] };
  } else if (!datastream && booleanTelemetry.has(id)) {
    datastream = { dataTypes: ["boolean"], directions: ["telemetry", "bidirectional"] };
  } else if (!datastream && id === "text_value") {
    datastream = { dataTypes: ["string", "integer", "double"], directions: ["telemetry", "bidirectional"] };
  } else if (!datastream && definition.category === "control") {
    datastream = { virtualOnly: true };
  }
  return datastream ? { ...definition, datastream } : definition;
}

export const widgetDefinitions: WidgetDefinition[] = [
  makeDefinition({
    id: "toggle_switch",
    legacyIds: ["switch"],
    label: "Công tắc bật/tắt",
    category: "control",
    icon: ToggleLeft,
    description: "Điều khiển bật/tắt với phản hồi telemetry và ghi đè GPIO.",
    bindingMode: "commandTelemetry",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: { color: "#22c55e", confirmBeforeSend: false, allowOfflineControl: false, hideTitle: false, showStateLabels: false, onLabel: "ON", offLabel: "OFF", labelPosition: "right" },
    configSchema: { valueType: "boolean" },
    validationRules: [],
    editorFields: [...controlFields, ...displayFields, ...toggleLabelFields, ...layoutFields],
    renderer: ControlWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: true, requiresTelemetryField: true, supportsManualTelemetry: true, supportsGpioOverride: true, capabilityTypes: ["digital_output", "relay", "led"] },
  }),
  makeDefinition({
    id: "push_button",
    legacyIds: ["button"],
    label: "Nút nhấn lệnh",
    category: "control",
    icon: MousePointerClick,
    description: "Nút nhấn một lần cho đầu ra kỹ thuật số hoặc lệnh.",
    bindingMode: "command",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: { confirmBeforeSend: false },
    configSchema: { valueType: "boolean" },
    validationRules: [],
    editorFields: [...controlFields, ...layoutFields],
    renderer: ControlWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: true, requiresTelemetryField: false, supportsGpioOverride: true, capabilityTypes: ["digital_output", "relay", "led"] },
  }),
  makeDefinition({
    id: "momentary_button",
    label: "Nút nhấn giữ / xung",
    category: "control",
    icon: TimerReset,
    description: "Gửi xung và tự động nhả sau thời gian cấu hình.",
    bindingMode: "commandTelemetry",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: { pulseDurationMs: 500, confirmBeforeSend: false },
    configSchema: { valueType: "boolean" },
    validationRules: [],
    editorFields: [...controlFields, ...pulseFields, ...layoutFields],
    renderer: ControlWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: true, requiresTelemetryField: true, supportsManualTelemetry: true, supportsGpioOverride: true, capabilityTypes: ["digital_output", "relay", "led"] },
  }),
  makeDefinition({
    id: "slider_control",
    label: "Thanh trượt điều khiển",
    category: "control",
    icon: SlidersHorizontal,
    description: "Điều khiển liên tục cho giá trị số hoặc lệnh mờ sáng.",
    bindingMode: "commandTelemetry",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: { min: 0, max: 100, step: 1, unit: "%" },
    configSchema: { valueType: "number" },
    validationRules: [],
    editorFields: [...numericFields, ...displayFields, ...controlFields, ...layoutFields],
    renderer: ControlWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: true, requiresTelemetryField: true, supportsManualTelemetry: true, supportsGpioOverride: true },
  }),
  makeDefinition({
    id: "knob_dial_control",
    label: "Knob / Dial Control",
    category: "control",
    icon: Gauge,
    description: "Compact dial-like control backed by numeric command values.",
    bindingMode: "commandTelemetry",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: { min: 0, max: 100, step: 1, unit: "%" },
    configSchema: { valueType: "number" },
    validationRules: [],
    editorFields: [...numericFields, ...displayFields, ...controlFields, ...layoutFields],
    renderer: ControlWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: true, requiresTelemetryField: true, supportsManualTelemetry: true, supportsGpioOverride: true },
    hidden: true,
  }),
  makeDefinition({
    id: "numeric_input",
    label: "Nhập giá trị số",
    category: "control",
    icon: Hash,
    description: "Nhập số với hỗ trợ min, max, bước và đơn vị.",
    bindingMode: "commandTelemetry",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: { min: 0, max: 100, step: 1 },
    configSchema: { valueType: "number" },
    validationRules: [],
    editorFields: [...numericFields, ...displayFields, ...controlFields, ...layoutFields],
    renderer: ControlWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: true, requiresTelemetryField: true, supportsManualTelemetry: true, supportsGpioOverride: true },
  }),
  makeDefinition({
    id: "dropdown_command_selector",
    label: "Chọn lệnh",
    category: "control",
    icon: ListFilter,
    description: "Chọn một giá trị lệnh từ danh sách thả xuống.",
    bindingMode: "commandTelemetry",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: { optionsCsv: "off,on" },
    configSchema: { valueType: "string" },
    validationRules: [],
    editorFields: [...optionFields, ...controlFields, ...layoutFields],
    renderer: ControlWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: true, requiresTelemetryField: true, supportsManualTelemetry: true, supportsGpioOverride: true },
  }),
  makeDefinition({
    id: "segmented_control",
    label: "Chọn chế độ",
    category: "control",
    icon: Rows3,
    description: "Chọn chế độ hoặc lệnh rời rạc từ các nút bấm trực tiếp.",
    bindingMode: "commandTelemetry",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: { optionsCsv: "off,on,auto" },
    configSchema: { valueType: "string" },
    validationRules: [],
    editorFields: [...optionFields, ...controlFields, ...layoutFields],
    renderer: ControlWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: true, requiresTelemetryField: true, supportsManualTelemetry: true, supportsGpioOverride: true },
  }),
  makeDefinition({
    id: "color_picker",
    label: "Color Picker",
    category: "control",
    icon: Palette,
    description: "Sends a color string or encoded value through the configured command.",
    bindingMode: "commandTelemetry",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: { color: "#22c55e" },
    configSchema: { valueType: "string" },
    validationRules: [],
    editorFields: [...displayFields, ...controlFields, ...layoutFields],
    renderer: ControlWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: true, requiresTelemetryField: true, supportsManualTelemetry: true, supportsGpioOverride: true },
    hidden: true,
  }),
  makeDefinition({
    id: "direction_pad_joystick",
    label: "Direction Pad / Joystick",
    category: "control",
    icon: Move,
    description: "Directional command pad for movement, pan/tilt, or navigation actions.",
    bindingMode: "command",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: {},
    configSchema: { valueType: "string" },
    validationRules: [],
    editorFields: [...controlFields, ...layoutFields],
    renderer: ControlWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: true, requiresTelemetryField: false, supportsGpioOverride: false },
    hidden: true,
  }),
  makeDefinition({
    id: "stepper_control",
    label: "Stepper Control",
    category: "control",
    icon: Gauge,
    description: "Increment or decrement a numeric command value in defined steps.",
    bindingMode: "commandTelemetry",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: { min: 0, max: 100, step: 5 },
    configSchema: { valueType: "number" },
    validationRules: [],
    editorFields: [...numericFields, ...controlFields, ...layoutFields],
    renderer: ControlWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: true, requiresTelemetryField: true, supportsManualTelemetry: true, supportsGpioOverride: true },
    hidden: true,
  }),
  makeDefinition({
    id: "schedule_button_timer",
    label: "Schedule Button / Timer Control",
    category: "control",
    icon: AlarmClock,
    description: "Manual trigger for timer or schedule-related commands with optional confirmation.",
    bindingMode: "command",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: { scheduleLabel: "Trigger schedule", confirmBeforeSend: true },
    configSchema: { valueType: "boolean" },
    validationRules: [],
    editorFields: [
      { key: "scheduleLabel", label: "Button label", labelKey: "projects:editor.ui.field.buttonLabel", kind: "text", scope: "config", section: "Behavior", placeholder: "Start irrigation", placeholderKey: "projects:editor.ui.placeholder.scheduleLabel" },
      ...controlFields,
      ...layoutFields,
    ],
    renderer: ControlWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: true, requiresTelemetryField: false, supportsGpioOverride: false },
    hidden: true,
  }),
  makeDefinition({
    id: "text_value",
    legacyIds: ["text"],
    label: "Giá trị văn bản",
    category: "display",
    icon: Type,
    description: "Hiển thị văn bản từ trường telemetry hoặc khóa trạng thái.",
    bindingMode: "telemetry",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: { decimalPlaces: 1 },
    configSchema: { valueType: "string" },
    validationRules: [],
    editorFields: [...displayFields, ...layoutFields],
    renderer: DisplayWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: false, requiresTelemetryField: true, supportsManualTelemetry: true },
  }),
  makeDefinition({
    id: "led_indicator",
    legacyIds: ["led"],
    label: "Đèn trạng thái",
    category: "display",
    icon: Lightbulb,
    description: "Đèn chỉ thị với ánh xạ màu và hỗ trợ phản hồi thiết bị.",
    bindingMode: "telemetry",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: { color: "#22c55e" },
    configSchema: { valueType: "boolean" },
    validationRules: [],
    editorFields: [...displayFields, ...layoutFields],
    renderer: DisplayWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: false, requiresTelemetryField: true, supportsManualTelemetry: true },
  }),
  makeDefinition({
    id: "icon_status",
    label: "Trạng thái biểu tượng",
    category: "display",
    icon: MonitorDot,
    description: "Ô trạng thái nhỏ cho giá trị boolean hoặc telemetry.",
    bindingMode: "telemetry",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: { color: "#22c55e" },
    configSchema: { valueType: "boolean" },
    validationRules: [],
    editorFields: [...displayFields, ...layoutFields],
    renderer: DisplayWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: false, requiresTelemetryField: true, supportsManualTelemetry: true },
  }),
  makeDefinition({
    id: "battery_indicator",
    label: "Mức pin",
    category: "display",
    icon: BatteryMedium,
    description: "Trạng thái pin hoặc sạc hiển thị trên thang tuyến tính.",
    bindingMode: "telemetry",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: { min: 0, max: 100, unit: "%", color: "#22c55e" },
    configSchema: { valueType: "number" },
    validationRules: [],
    editorFields: [...numericFields, ...displayFields, ...layoutFields],
    renderer: DisplayWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: false, requiresTelemetryField: true, supportsManualTelemetry: true },
  }),
  makeDefinition({
    id: "signal_strength_wifi_rssi",
    label: "Tín hiệu WiFi",
    category: "display",
    icon: Signal,
    description: "Tín hiệu RSSI hoặc WiFi hiển thị dưới dạng thanh cường độ.",
    bindingMode: "telemetry",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: { min: -100, max: -20, unit: "dBm", color: "#0ea5e9" },
    configSchema: { valueType: "number" },
    validationRules: [],
    editorFields: [...numericFields, ...displayFields, ...layoutFields],
    renderer: DisplayWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: false, requiresTelemetryField: true, supportsManualTelemetry: true },
  }),
  makeDefinition({
    id: "progress_bar",
    label: "Thanh tiến trình",
    category: "display",
    icon: Activity,
    description: "Thanh tiến trình tuyến tính cho phần trăm hoặc giá trị số có giới hạn.",
    bindingMode: "telemetry",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: { min: 0, max: 100, unit: "%", color: "#2563eb" },
    configSchema: { valueType: "number" },
    validationRules: [],
    editorFields: [...numericFields, ...displayFields, ...layoutFields],
    renderer: DisplayWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: false, requiresTelemetryField: true, supportsManualTelemetry: true },
  }),
  makeDefinition({
    id: "thermometer",
    label: "Thermometer",
    category: "display",
    icon: Thermometer,
    description: "Temperature-oriented value card with scale-aware presentation.",
    bindingMode: "telemetry",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: { min: 0, max: 100, unit: "°C", color: "#f97316" },
    configSchema: { valueType: "number" },
    validationRules: [],
    editorFields: [...numericFields, ...displayFields, ...layoutFields],
    renderer: DisplayWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: false, requiresTelemetryField: true, supportsManualTelemetry: true },
    hidden: true,
  }),
  makeDefinition({
    id: "humidity_card",
    label: "Humidity Card",
    category: "display",
    icon: Droplets,
    description: "Humidity telemetry displayed with scale and friendly unit formatting.",
    bindingMode: "telemetry",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: { min: 0, max: 100, unit: "%", color: "#0ea5e9" },
    configSchema: { valueType: "number" },
    validationRules: [],
    editorFields: [...numericFields, ...displayFields, ...layoutFields],
    renderer: DisplayWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: false, requiresTelemetryField: true, supportsManualTelemetry: true },
    hidden: true,
  }),
  makeDefinition({
    id: "number_card",
    legacyIds: ["humidity_card", "thermometer"],
    label: "Thẻ giá trị số",
    category: "display",
    icon: Hash,
    description: "Thẻ giá trị số với đơn vị, tiền tố, hậu tố và số thập phân.",
    bindingMode: "telemetry",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: { decimalPlaces: 1, color: "#2563eb" },
    configSchema: { valueType: "number" },
    validationRules: [],
    editorFields: [...numericFields, ...displayFields, ...layoutFields],
    renderer: DisplayWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: false, requiresTelemetryField: true, supportsManualTelemetry: true },
  }),
  makeDefinition({
    id: "circular_gauge",
    label: "Circular Gauge",
    category: "display",
    icon: Gauge,
    description: "Gauge-styled numeric readout with min/max bounds and color accent.",
    bindingMode: "telemetry",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: { min: 0, max: 100, decimalPlaces: 1, color: "#2563eb" },
    configSchema: { valueType: "number" },
    validationRules: [],
    editorFields: [...numericFields, ...displayFields, ...layoutFields],
    renderer: DisplayWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: false, requiresTelemetryField: true, supportsManualTelemetry: true },
    hidden: true,
  }),
  makeDefinition({
    id: "linear_gauge",
    label: "Linear Gauge",
    category: "display",
    icon: Gauge,
    description: "Bar-based gauge for bounded numeric values and sensor progress.",
    bindingMode: "telemetry",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: { min: 0, max: 100, decimalPlaces: 1, color: "#8b5cf6" },
    configSchema: { valueType: "number" },
    validationRules: [],
    editorFields: [...numericFields, ...displayFields, ...layoutFields],
    renderer: DisplayWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: false, requiresTelemetryField: true, supportsManualTelemetry: true },
    hidden: true,
  }),
  makeDefinition({
    id: "gauge_widget",
    legacyIds: ["circular_gauge", "linear_gauge", "gauge"],
    label: "Đồng hồ đo",
    category: "display",
    icon: Gauge,
    description: "Đồng hồ đo số với kiểu hiển thị tròn hoặc tuyến tính.",
    bindingMode: "telemetry",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: { min: 0, max: 100, decimalPlaces: 1, color: "#2563eb", displayStyle: "circular" },
    configSchema: { valueType: "number" },
    validationRules: [],
    editorFields: [
      ...numericFields,
      ...displayFields,
      { key: "displayStyle", label: "Display style", kind: "select", scope: "config", section: "Display", options: [{ label: "Circular", value: "circular" }, { label: "Linear", value: "linear" }] },
      ...layoutFields,
    ],
    renderer: DisplayWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: false, requiresTelemetryField: true, supportsManualTelemetry: true },
  }),
  makeDefinition({
    id: "multi_value_card",
    label: "Thẻ nhiều giá trị",
    category: "display",
    icon: SquareStack,
    description: "Hiển thị nhiều trường telemetry liên quan trong một thẻ.",
    bindingMode: "telemetry",
    defaultSize: { colSpan: 2, rowSpan: 1 },
    defaultConfig: { fields: [] },
    configSchema: { valueType: "mixed" },
    validationRules: [],
    editorFields: [
      { key: "fieldsCsv", label: "Fields", kind: "text", scope: "config", section: "Display", placeholder: "temperature,humidity,battery", description: "Comma-separated telemetry fields." },
      ...displayFields,
      ...layoutFields,
    ],
    renderer: DisplayWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: false, requiresTelemetryField: true, supportsManualTelemetry: true },
  }),
  makeDefinition({
    id: "device_online_status",
    label: "Trạng thái thiết bị",
    category: "display",
    icon: Wifi,
    description: "Thẻ sức khỏe thiết bị hiển thị trạng thái trực tuyến/ngoại tuyến.",
    bindingMode: "telemetry",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: { color: "#22c55e" },
    configSchema: { valueType: "boolean" },
    validationRules: [],
    editorFields: [...displayFields, ...layoutFields],
    renderer: DisplayWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: false, requiresTelemetryField: false, supportsManualTelemetry: true },
  }),
  makeDefinition({
    id: "last_seen_card",
    label: "Lần cập nhật cuối",
    category: "display",
    icon: Clock3,
    description: "Hiển thị thời gian cập nhật telemetry cuối cùng của thiết bị.",
    bindingMode: "telemetry",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: {},
    configSchema: { valueType: "datetime" },
    validationRules: [],
    editorFields: [...layoutFields],
    renderer: DisplayWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: false, requiresTelemetryField: false, supportsManualTelemetry: true },
  }),
  makeDefinition({
    id: "line_chart",
    label: "Line Chart",
    category: "chart",
    icon: Waves,
    description: "Historical telemetry line chart with refresh interval and point limit controls.",
    bindingMode: "telemetry",
    defaultSize: { colSpan: 2, rowSpan: 1 },
    defaultConfig: { timeRange: "6h", refreshIntervalSeconds: 15, aggregation: "avg", maxDataPoints: 60, color: "#2563eb" },
    configSchema: { valueType: "series" },
    validationRules: [],
    editorFields: [...chartFields, ...displayFields, ...layoutFields],
    renderer: ChartWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: false, requiresTelemetryField: true, supportsManualTelemetry: true },
    hidden: true,
  }),
  makeDefinition({
    id: "area_chart",
    label: "Area Chart",
    category: "chart",
    icon: Activity,
    description: "Filled area chart for smoother trend visualization.",
    bindingMode: "telemetry",
    defaultSize: { colSpan: 2, rowSpan: 1 },
    defaultConfig: { timeRange: "6h", refreshIntervalSeconds: 15, aggregation: "avg", maxDataPoints: 60, color: "#0ea5e9" },
    configSchema: { valueType: "series" },
    validationRules: [],
    editorFields: [...chartFields, ...displayFields, ...layoutFields],
    renderer: ChartWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: false, requiresTelemetryField: true, supportsManualTelemetry: true },
    hidden: true,
  }),
  makeDefinition({
    id: "bar_chart",
    label: "Bar Chart",
    category: "chart",
    icon: Activity,
    description: "Discrete bar chart for sampled numeric telemetry.",
    bindingMode: "telemetry",
    defaultSize: { colSpan: 2, rowSpan: 1 },
    defaultConfig: { timeRange: "6h", refreshIntervalSeconds: 30, aggregation: "avg", maxDataPoints: 40, color: "#8b5cf6" },
    configSchema: { valueType: "series" },
    validationRules: [],
    editorFields: [...chartFields, ...displayFields, ...layoutFields],
    renderer: ChartWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: false, requiresTelemetryField: true, supportsManualTelemetry: true },
    hidden: true,
  }),
  makeDefinition({
    id: "donut_pie_chart",
    label: "Donut / Pie Chart",
    category: "chart",
    icon: PieChart,
    description: "Compact pie-style chart for recent distribution snapshots.",
    bindingMode: "telemetry",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: { timeRange: "6h", refreshIntervalSeconds: 30, aggregation: "avg", maxDataPoints: 12, color: "#f59e0b" },
    configSchema: { valueType: "series" },
    validationRules: [],
    editorFields: [...chartFields, ...displayFields, ...layoutFields],
    renderer: ChartWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: false, requiresTelemetryField: true, supportsManualTelemetry: true },
    hidden: true,
  }),
  makeDefinition({
    id: "sparkline",
    label: "Đường xu hướng nhỏ",
    category: "chart",
    icon: Waves,
    description: "Đường xu hướng nhỏ cho bảng điều khiển dày đặc hoặc thẻ tóm tắt.",
    bindingMode: "telemetry",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: { timeRange: "live", refreshIntervalSeconds: 15, aggregation: "avg", maxDataPoints: 40, color: "#22c55e" },
    hidden: true,
    configSchema: { valueType: "series" },
    validationRules: [],
    editorFields: [...chartFields, ...displayFields, ...layoutFields],
    renderer: ChartWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: false, requiresTelemetryField: true, supportsManualTelemetry: true },
  }),
  makeDefinition({
    id: "realtime_mini_chart",
    label: "Biểu đồ live nhỏ",
    category: "chart",
    icon: Activity,
    description: "Biểu đồ nhỏ tần số cao cho phản hồi telemetry thời gian thực.",
    bindingMode: "telemetry",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: { chartType: "bar", timeRange: "live", refreshIntervalSeconds: 10, aggregation: "avg", maxDataPoints: 30, color: "#ef4444", showGrid: true, showXAxis: true, showYAxis: true, connectNulls: true, decimalPlaces: 2 },
    configSchema: { valueType: "series" },
    validationRules: [],
    editorFields: [...chartFields, ...displayFields, ...layoutFields],
    renderer: ChartWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: false, requiresTelemetryField: true, supportsManualTelemetry: true },
  }),
  makeDefinition({
    id: "historical_telemetry_chart",
    label: "Historical Telemetry Chart",
    category: "chart",
    icon: Activity,
    description: "Longer-range telemetry chart for historical analysis and trend review.",
    bindingMode: "telemetry",
    defaultSize: { colSpan: 2, rowSpan: 1 },
    defaultConfig: { timeRange: "1d", refreshIntervalSeconds: 60, aggregation: "avg", maxDataPoints: 120, color: "#2563eb" },
    configSchema: { valueType: "series" },
    validationRules: [],
    editorFields: [...chartFields, ...displayFields, ...layoutFields],
    renderer: ChartWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: false, requiresTelemetryField: true, supportsManualTelemetry: true },
    hidden: true,
  }),
  makeDefinition({
    id: "telemetry_chart",
    legacyIds: ["line_chart", "area_chart", "bar_chart", "historical_telemetry_chart"],
    label: "Biểu đồ telemetry",
    category: "chart",
    icon: Waves,
    description: "Biểu đồ telemetry hỗ trợ chế độ đường, vùng và cột.",
    bindingMode: "telemetry",
    defaultSize: { colSpan: 2, rowSpan: 1 },
    defaultConfig: { chartType: "line", curveType: "monotone", timeRange: "6h", refreshIntervalSeconds: 15, aggregation: "avg", maxDataPoints: 60, color: "#2563eb", showGrid: true, showXAxis: true, showYAxis: true, connectNulls: true, decimalPlaces: 2 },
    configSchema: { valueType: "series" },
    validationRules: [],
    editorFields: [...chartFields, ...displayFields, ...layoutFields],
    renderer: ChartWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: false, requiresTelemetryField: true, supportsManualTelemetry: true },
  }),
  makeDefinition({
    id: "multi_telemetry_chart",
    label: "Biểu đồ đa kênh",
    category: "chart",
    icon: Waves,
    description: "Biểu đồ vẽ nhiều đường hoặc cột cho nhiều Datastream khác nhau.",
    bindingMode: "telemetry",
    defaultSize: { colSpan: 2, rowSpan: 1 },
    defaultConfig: { chartType: "line", curveType: "monotone", timeRange: "6h", refreshIntervalSeconds: 15, aggregation: "avg", maxDataPoints: 60, showGrid: true, showXAxis: true, showYAxis: true, showLegend: true, connectNulls: true, decimalPlaces: 2 },
    configSchema: { valueType: "series" },
    validationRules: [],
    editorFields: [...chartFields, ...displayFields, ...layoutFields],
    renderer: ChartWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: false, requiresTelemetryField: false, supportsManualTelemetry: true },
    hidden: false,
  }),
  makeDefinition({
    id: "alarm_badge",
    label: "Nhãn cảnh báo",
    category: "status",
    icon: Bell,
    description: "Nhãn cảnh báo nhỏ cho telemetry boolean hoặc cảnh báo rời rạc.",
    bindingMode: "telemetry",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: { color: "#ef4444" },
    configSchema: { valueType: "boolean" },
    validationRules: [],
    editorFields: [...displayFields, ...layoutFields],
    renderer: StatusWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: false, requiresTelemetryField: true, supportsManualTelemetry: true },
  }),
  makeDefinition({
    id: "threshold_alert_card",
    label: "Cảnh báo ngưỡng",
    category: "status",
    icon: AlertTriangle,
    description: "Đánh giá telemetry so với ngưỡng cảnh báo và nguy hiểm.",
    bindingMode: "telemetry",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: { warningThreshold: 70, dangerThreshold: 90, thresholdCondition: "above", color: "#f59e0b" },
    configSchema: { valueType: "number" },
    validationRules: [],
    editorFields: [...numericFields, ...thresholdFields, ...displayFields, ...layoutFields],
    renderer: StatusWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: false, requiresTelemetryField: true, supportsManualTelemetry: true },
  }),
  makeDefinition({
    id: "boolean_status_card",
    label: "Trạng thái đúng/sai",
    category: "status",
    icon: MonitorDot,
    description: "Hiển thị trạng thái boolean với nhãn và thông báo trực quan.",
    bindingMode: "telemetry",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: { color: "#22c55e" },
    configSchema: { valueType: "boolean" },
    validationRules: [],
    editorFields: [...displayFields, ...layoutFields],
    renderer: StatusWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: false, requiresTelemetryField: true, supportsManualTelemetry: true },
  }),
  makeDefinition({
    id: "error_state_card",
    label: "Trạng thái lỗi",
    category: "status",
    icon: AlertTriangle,
    description: "Nhấn mạnh telemetry lỗi hoặc sự cố với giao diện trực quan mạnh mẽ.",
    bindingMode: "telemetry",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: { color: "#ef4444" },
    configSchema: { valueType: "mixed" },
    validationRules: [],
    editorFields: [...displayFields, ...layoutFields],
    renderer: StatusWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: false, requiresTelemetryField: true, supportsManualTelemetry: true },
  }),
  makeDefinition({
    id: "firmware_update_status",
    label: "Trạng thái firmware",
    category: "status",
    icon: MonitorDot,
    description: "Hiển thị trạng thái cập nhật firmware từ telemetry thiết bị.",
    bindingMode: "telemetry",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: {},
    configSchema: { valueType: "string" },
    validationRules: [],
    editorFields: [...layoutFields],
    renderer: StatusWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: false, requiresTelemetryField: true, supportsManualTelemetry: true },
  }),
  makeDefinition({
    id: "ota_job_status",
    label: "Trạng thái OTA",
    category: "status",
    icon: Activity,
    description: "Thẻ tiến trình OTA hoặc trạng thái công việc cho bảng điều khiển firmware.",
    bindingMode: "telemetry",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: { min: 0, max: 100, unit: "%" },
    configSchema: { valueType: "number" },
    validationRules: [],
    editorFields: [...numericFields, ...displayFields, ...layoutFields],
    renderer: StatusWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: false, requiresTelemetryField: true, supportsManualTelemetry: true },
  }),


  makeDefinition({
    id: "label_text_block",
    label: "Nhãn / văn bản",
    category: "utility",
    icon: Type,
    description: "Khung văn bản tĩnh để gắn nhãn hoặc giải thích khu vực bảng điều khiển.",
    bindingMode: "static",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: { text: "Section label" },
    configSchema: { valueType: "static" },
    validationRules: [],
    editorFields: [...textFields, ...displayFields, ...layoutFields],
    renderer: UtilityWidgetRenderer,
    binding: { requiresDevice: false, requiresCapability: false, requiresTelemetryField: false },
  }),
  makeDefinition({
    id: "divider",
    label: "Divider",
    category: "utility",
    icon: Minus,
    description: "Visual divider to break up widget groups without changing the grid layout.",
    bindingMode: "static",
    defaultSize: { colSpan: 2, rowSpan: 1 },
    defaultConfig: {},
    configSchema: { valueType: "static" },
    validationRules: [],
    editorFields: [...layoutFields],
    renderer: UtilityWidgetRenderer,
    binding: { requiresDevice: false, requiresCapability: false, requiresTelemetryField: false },
    hidden: true,
  }),
  makeDefinition({
    id: "image_card",
    label: "Image Card",
    category: "utility",
    icon: ImageIcon,
    description: "Static image card for diagrams, labels, or quick reference visuals.",
    bindingMode: "static",
    defaultSize: { colSpan: 2, rowSpan: 1 },
    defaultConfig: { imageUrl: "" },
    configSchema: { valueType: "static" },
    validationRules: [],
    editorFields: [...imageFields, ...layoutFields],
    renderer: UtilityWidgetRenderer,
    binding: { requiresDevice: false, requiresCapability: false, requiresTelemetryField: false },
    hidden: true,
  }),
  makeDefinition({
    id: "group_box_panel",
    label: "Khung nhóm",
    category: "utility",
    icon: SquareStack,
    description: "Bảng tĩnh có tiêu đề giúp tổ chức khu vực bảng điều khiển.",
    bindingMode: "static",
    defaultSize: { colSpan: 2, rowSpan: 1 },
    defaultConfig: { text: "Panel note" },
    configSchema: { valueType: "static" },
    validationRules: [],
    editorFields: [...textFields, ...layoutFields],
    renderer: UtilityWidgetRenderer,
    binding: { requiresDevice: false, requiresCapability: false, requiresTelemetryField: false },
  }),
  makeDefinition({
    id: "markdown_note",
    label: "Ghi chú Markdown",
    category: "utility",
    icon: Type,
    description: "Ghi chú định dạng phong phú cho hướng dẫn vận hành hoặc sử dụng thiết bị.",
    bindingMode: "static",
    defaultSize: { colSpan: 2, rowSpan: 1 },
    defaultConfig: { markdown: "## Dashboard note" },
    configSchema: { valueType: "static" },
    validationRules: [],
    editorFields: [...markdownFields, ...layoutFields],
    renderer: UtilityWidgetRenderer,
    binding: { requiresDevice: false, requiresCapability: false, requiresTelemetryField: false },
  }),
  makeDefinition({
    id: "device_info_card",
    label: "Thông tin thiết bị",
    category: "utility",
    icon: Info,
    description: "Thẻ thông tin cho thiết bị đang kết nối và chi tiết nhận dạng cơ bản.",
    bindingMode: "telemetry",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: {},
    configSchema: { valueType: "context" },
    validationRules: [],
    editorFields: [...layoutFields],
    renderer: UtilityWidgetRenderer,
    binding: { requiresDevice: true, requiresCapability: false, requiresTelemetryField: false, supportsManualTelemetry: true },
  }),
  makeDefinition({
    id: "project_info_card",
    label: "Thông tin project",
    category: "utility",
    icon: Info,
    description: "Thẻ tóm tắt project tĩnh hoạt động không cần kết nối thiết bị.",
    bindingMode: "static",
    defaultSize: { colSpan: 1, rowSpan: 1 },
    defaultConfig: {},
    configSchema: { valueType: "context" },
    validationRules: [],
    editorFields: [...layoutFields],
    renderer: UtilityWidgetRenderer,
    binding: { requiresDevice: false, requiresCapability: false, requiresTelemetryField: false },
  }),
];

const aliasMap = new Map<string, WidgetDefinition>();
for (const definition of widgetDefinitions) {
  aliasMap.set(definition.id, definition);
  for (const legacyId of definition.legacyIds ?? []) {
    aliasMap.set(legacyId, definition);
  }
}

const fallbackDefinition = widgetDefinitions.find((item) => item.id === "text_value") ?? widgetDefinitions[0];

export function resolveWidgetDefinition(widgetType: string): WidgetDefinition {
  return aliasMap.get(widgetType) ?? fallbackDefinition;
}

export function listWidgetDefinitions(search = "", includeHidden = false): WidgetDefinition[] {
  const query = search.trim().toLowerCase();
  const items = widgetDefinitions
    .filter((definition) => {
      if (!includeHidden && definition.hidden) return false;
      if (!query) return true;
      return `${definition.label} ${definition.description} ${definition.id}`.toLowerCase().includes(query);
    })
    .sort((a, b) => a.category.localeCompare(b.category) || a.label.localeCompare(b.label));
  return items;
}

export const ALL_WIDGET_TYPE_IDS = widgetDefinitions.flatMap((definition) => [definition.id, ...(definition.legacyIds ?? [])]);
