from datetime import datetime, timezone
from types import SimpleNamespace
from uuid import uuid4

from app import main as _app_main  # noqa: F401 - registers SQLAlchemy models
from app.bounded_contexts.telemetry.infrastructure.persistence.alert_models import Alert
from app.bounded_contexts.telemetry.presentation import admin_alerts_router


def _device(**overrides):
    values = {
        "id": uuid4(),
        "tenant_id": uuid4(),
        "device_uid": "esp32-test-001",
        "name": "Test Node",
        "status": "online",
        "last_seen_at": datetime.now(timezone.utc),
        "rssi": -62,
        "uptime_ms": 3_600_000,
        "offline_timeout_seconds": 60,
        "metadata_": {},
    }
    values.update(overrides)
    return SimpleNamespace(**values)


class _AdminAlertDb:
    def __init__(self, alert, device):
        self.alert = alert
        self.device = device
        self.commits = 0

    def scalars(self, _statement):
        return SimpleNamespace(all=lambda: [self.alert])

    def get(self, model, _identifier):
        return self.alert if model is Alert else self.device

    def commit(self):
        self.commits += 1

    def refresh(self, _item):
        return None


def test_admin_alert_api_returns_and_updates_persistent_alert(monkeypatch):
    now = datetime.now(timezone.utc)
    # Use a platform-owned device (tenant_id=None): admin can acknowledge/resolve
    # alerts generated by platform-managed devices.
    device = _device(tenant_id=None)
    alert = Alert(
        tenant_id=None,  # platform-owned: admin has full access
        device_id=device.id,
        severity="critical",
        status="open",
        source="automation",
        code="automation:temperature",
        title="Automation threshold reached",
        message="temperature exceeded configured threshold",
        details={"temperature": 32.0},
        first_seen_at=now,
        last_seen_at=now,
    )
    alert.id = uuid4()
    db = _AdminAlertDb(alert, device)
    monkeypatch.setattr(admin_alerts_router.tenant_repository, "get_tenant", lambda *_: None)

    rows = admin_alerts_router.list_admin_alerts(
        severity=None,
        alert_status=None,
        source_type=None,
        device_id=None,
        device_uid=None,
        from_time=None,
        to_time=None,
        limit=100,
        offset=0,
        page=None,
        db=db,
    )
    acknowledged = admin_alerts_router.acknowledge_admin_alert(
        alert.id, current_admin=SimpleNamespace(id=uuid4()), db=db
    )
    resolved = admin_alerts_router.resolve_admin_alert(alert.id, db=db)

    assert rows[0]["source_type"] == "automation"
    assert acknowledged["status"] == "acknowledged"
    assert resolved["status"] == "resolved"
    assert db.commits == 2
