"""Add public_site_config to system_settings

Revision ID: 0007
Revises: 0006
Create Date: 2026-07-05 22:30:06.339627
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0007"
down_revision: Union[str, None] = "0006"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "alerts",
        "first_seen_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "alerts",
        "last_seen_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "alerts",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "alerts",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index("idx_alerts_device_created_at", table_name="alerts")
    op.drop_index("idx_alerts_source_code", table_name="alerts")
    op.drop_index("idx_alerts_status_severity", table_name="alerts")
    op.drop_index("idx_alerts_tenant_created_at", table_name="alerts")
    op.alter_column(
        "anomaly_events",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "api_doc_overrides",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "api_doc_overrides",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "audit_logs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        "idx_audit_logs_ip_address",
        table_name="audit_logs",
        postgresql_where="(ip_address IS NOT NULL)",
    )
    op.drop_index("idx_audit_logs_tenant_created_at", table_name="audit_logs")
    op.drop_index(
        "idx_automation_rule_executions_device_id", table_name="automation_rule_executions"
    )
    op.drop_index("idx_automation_rule_executions_rule_id", table_name="automation_rule_executions")
    op.drop_index(
        "idx_automation_rule_executions_tenant_id", table_name="automation_rule_executions"
    )
    op.create_index(
        op.f("ix_automation_rule_executions_device_id"),
        "automation_rule_executions",
        ["device_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_automation_rule_executions_rule_id"),
        "automation_rule_executions",
        ["rule_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_automation_rule_executions_tenant_id"),
        "automation_rule_executions",
        ["tenant_id"],
        unique=False,
    )
    op.drop_index("idx_automation_rules_project_id", table_name="automation_rules")
    op.drop_index("idx_automation_rules_tenant_id", table_name="automation_rules")
    op.create_index(
        op.f("ix_automation_rules_project_id"), "automation_rules", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_automation_rules_tenant_id"), "automation_rules", ["tenant_id"], unique=False
    )
    op.alter_column(
        "capability_templates",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "capability_templates",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "command_dispatches",
        "retry_count",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "command_dispatches",
        "max_retries",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("3"),
    )
    op.alter_column(
        "command_dispatches",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "command_dispatches",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index("idx_command_dispatches_status", table_name="command_dispatches")
    op.drop_index("idx_command_dispatches_tenant_created", table_name="command_dispatches")
    op.drop_index("idx_command_dispatches_tenant_id", table_name="command_dispatches")
    op.create_index(
        op.f("ix_command_dispatches_tenant_id"), "command_dispatches", ["tenant_id"], unique=False
    )
    op.alter_column(
        "command_targets",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "command_targets",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index("idx_command_targets_device_id", table_name="command_targets")
    op.drop_index("idx_command_targets_dispatch_id", table_name="command_targets")
    op.drop_constraint("uq_command_targets_dispatch_device", "command_targets", type_="unique")
    op.create_index(
        op.f("ix_command_targets_device_id"), "command_targets", ["device_id"], unique=False
    )
    op.create_index(
        op.f("ix_command_targets_dispatch_id"), "command_targets", ["dispatch_id"], unique=False
    )
    op.alter_column(
        "command_templates",
        "is_system",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "command_templates",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "command_templates",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index("idx_command_templates_tenant_id", table_name="command_templates")
    op.create_index(
        op.f("ix_command_templates_tenant_id"), "command_templates", ["tenant_id"], unique=False
    )
    op.alter_column(
        "device_capabilities",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "device_capabilities",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "device_credentials",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index("idx_device_credentials_type", table_name="device_credentials")
    op.alter_column(
        "device_group_members",
        "added_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "device_groups",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "device_groups",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index("idx_device_groups_tenant_created_at", table_name="device_groups")
    op.create_index("idx_device_groups_status", "device_groups", ["status"], unique=False)
    op.alter_column(
        "device_health",
        "uptime_ms",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.drop_index("device_health_time_idx", table_name="device_health")
    op.drop_index("idx_device_health_device_time", table_name="device_health")
    op.drop_index("idx_device_health_uid_time", table_name="device_health")
    op.create_table_comment(
        "device_health",
        "Time-series device health metrics (may be hypertable)",
        existing_comment=None,
        schema=None,
    )
    op.alter_column(
        "device_models",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "device_models",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "device_platforms",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "device_platforms",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index("device_status_events_time_idx", table_name="device_status_events")
    op.drop_index("idx_device_status_events_device_time", table_name="device_status_events")
    op.drop_index("idx_device_status_events_uid_time", table_name="device_status_events")
    op.create_table_comment(
        "device_status_events",
        "Time-series device status transitions (may be hypertable)",
        existing_comment=None,
        schema=None,
    )
    op.alter_column(
        "device_types",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "device_types",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint("device_types_key_key", "device_types", type_="unique")
    op.drop_index("idx_device_types_key", table_name="device_types")
    op.create_index(op.f("ix_device_types_key"), "device_types", ["key"], unique=True)
    op.alter_column(
        "devices",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "devices",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index("idx_devices_device_type_id", table_name="devices")
    op.drop_index("idx_devices_hardware_model", table_name="devices")
    op.drop_index("idx_devices_last_seen_at", table_name="devices")
    op.drop_index("idx_devices_status", table_name="devices")
    op.create_index(op.f("ix_devices_device_type_id"), "devices", ["device_type_id"], unique=False)
    op.alter_column(
        "firmware_profiles",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "firmware_profiles",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index("idx_firmware_profiles_device_type", table_name="firmware_profiles")
    op.alter_column(
        "firmware_versions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        "idx_firmware_tenant_type",
        table_name="firmware_versions",
        postgresql_where="(uploaded_by_tenant_id IS NOT NULL)",
    )
    op.drop_index(
        "uq_firmware_global_version",
        table_name="firmware_versions",
        postgresql_where="(uploaded_by_tenant_id IS NULL)",
    )
    op.drop_index(
        "uq_firmware_tenant_version",
        table_name="firmware_versions",
        postgresql_where="(uploaded_by_tenant_id IS NOT NULL)",
    )
    op.drop_index(
        "uq_firmware_version_type_global",
        table_name="firmware_versions",
        postgresql_where="(uploaded_by_tenant_id IS NULL)",
    )
    op.drop_index(
        "uq_firmware_version_type_tenant",
        table_name="firmware_versions",
        postgresql_where="(uploaded_by_tenant_id IS NOT NULL)",
    )
    op.drop_index("health_scores_time_idx", table_name="health_scores")
    op.drop_index("idx_health_scores_device_time", table_name="health_scores")
    op.drop_index("idx_health_scores_uid_time", table_name="health_scores")
    op.alter_column(
        "intelligence_profiles",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "intelligence_profiles",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index("idx_intelligence_profiles_active", table_name="intelligence_profiles")
    op.drop_index("idx_intelligence_profiles_type", table_name="intelligence_profiles")
    op.create_index(
        op.f("ix_intelligence_profiles_is_active"),
        "intelligence_profiles",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_intelligence_profiles_profile_type"),
        "intelligence_profiles",
        ["profile_type"],
        unique=False,
    )
    op.alter_column(
        "ml_anomaly_events",
        "detected_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "ml_anomaly_events",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "ml_anomaly_events",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index("idx_ml_anomaly_events_dedup_key", table_name="ml_anomaly_events")
    op.drop_index("idx_ml_anomaly_events_detected_at", table_name="ml_anomaly_events")
    op.drop_index("idx_ml_anomaly_events_device_id", table_name="ml_anomaly_events")
    op.drop_index("idx_ml_anomaly_events_inference_result_id", table_name="ml_anomaly_events")
    op.drop_index("idx_ml_anomaly_events_model_version_id", table_name="ml_anomaly_events")
    op.drop_index("idx_ml_anomaly_events_severity", table_name="ml_anomaly_events")
    op.drop_index("idx_ml_anomaly_events_status", table_name="ml_anomaly_events")
    op.drop_index("idx_ml_anomaly_events_tenant_id", table_name="ml_anomaly_events")
    op.create_index(
        op.f("ix_ml_anomaly_events_dedup_key"), "ml_anomaly_events", ["dedup_key"], unique=False
    )
    op.create_index(
        op.f("ix_ml_anomaly_events_detected_at"), "ml_anomaly_events", ["detected_at"], unique=False
    )
    op.create_index(
        op.f("ix_ml_anomaly_events_device_id"), "ml_anomaly_events", ["device_id"], unique=False
    )
    op.create_index(
        op.f("ix_ml_anomaly_events_inference_result_id"),
        "ml_anomaly_events",
        ["inference_result_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ml_anomaly_events_model_version_id"),
        "ml_anomaly_events",
        ["model_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ml_anomaly_events_severity"), "ml_anomaly_events", ["severity"], unique=False
    )
    op.create_index(
        op.f("ix_ml_anomaly_events_status"), "ml_anomaly_events", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_ml_anomaly_events_tenant_id"), "ml_anomaly_events", ["tenant_id"], unique=False
    )
    op.alter_column(
        "ml_inference_results",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index("idx_ml_inference_results_algorithm", table_name="ml_inference_results")
    op.drop_index("idx_ml_inference_results_created_at", table_name="ml_inference_results")
    op.drop_index("idx_ml_inference_results_device_id", table_name="ml_inference_results")
    op.drop_index("idx_ml_inference_results_is_anomaly", table_name="ml_inference_results")
    op.drop_index("idx_ml_inference_results_model_id", table_name="ml_inference_results")
    op.drop_index("idx_ml_inference_results_model_version_id", table_name="ml_inference_results")
    op.drop_index("idx_ml_inference_results_prediction", table_name="ml_inference_results")
    op.drop_index("idx_ml_inference_results_runtime", table_name="ml_inference_results")
    op.drop_index("idx_ml_inference_results_tenant_id", table_name="ml_inference_results")
    op.create_index(
        op.f("ix_ml_inference_results_algorithm"),
        "ml_inference_results",
        ["algorithm"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ml_inference_results_created_at"),
        "ml_inference_results",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ml_inference_results_device_id"),
        "ml_inference_results",
        ["device_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ml_inference_results_is_anomaly"),
        "ml_inference_results",
        ["is_anomaly"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ml_inference_results_model_id"), "ml_inference_results", ["model_id"], unique=False
    )
    op.create_index(
        op.f("ix_ml_inference_results_model_version_id"),
        "ml_inference_results",
        ["model_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ml_inference_results_prediction"),
        "ml_inference_results",
        ["prediction"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ml_inference_results_runtime"), "ml_inference_results", ["runtime"], unique=False
    )
    op.create_index(
        op.f("ix_ml_inference_results_tenant_id"),
        "ml_inference_results",
        ["tenant_id"],
        unique=False,
    )
    op.alter_column(
        "ml_model_versions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "ml_model_versions",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index("idx_ml_model_versions_algorithm", table_name="ml_model_versions")
    op.drop_index("idx_ml_model_versions_is_active", table_name="ml_model_versions")
    op.drop_index("idx_ml_model_versions_stage", table_name="ml_model_versions")
    op.drop_index("idx_ml_model_versions_status", table_name="ml_model_versions")
    op.drop_index("idx_ml_model_versions_tenant_id", table_name="ml_model_versions")
    op.create_index(
        op.f("ix_ml_model_versions_algorithm"), "ml_model_versions", ["algorithm"], unique=False
    )
    op.create_index(
        op.f("ix_ml_model_versions_is_active"), "ml_model_versions", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_ml_model_versions_stage"), "ml_model_versions", ["stage"], unique=False
    )
    op.create_index(
        op.f("ix_ml_model_versions_status"), "ml_model_versions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_ml_model_versions_tenant_id"), "ml_model_versions", ["tenant_id"], unique=False
    )
    op.drop_constraint(
        "fk_ml_model_versions_training_job_id", "ml_model_versions", type_="foreignkey"
    )
    op.alter_column(
        "ml_models",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "ml_models",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index("idx_ml_models_problem_type", table_name="ml_models")
    op.drop_index("idx_ml_models_status", table_name="ml_models")
    op.drop_index("idx_ml_models_task_type", table_name="ml_models")
    op.drop_index("idx_ml_models_tenant_id", table_name="ml_models")
    op.create_index(op.f("ix_ml_models_problem_type"), "ml_models", ["problem_type"], unique=False)
    op.create_index(op.f("ix_ml_models_status"), "ml_models", ["status"], unique=False)
    op.create_index(op.f("ix_ml_models_task_type"), "ml_models", ["task_type"], unique=False)
    op.create_index(op.f("ix_ml_models_tenant_id"), "ml_models", ["tenant_id"], unique=False)
    op.alter_column(
        "ml_training_jobs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "ml_training_jobs",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index("idx_ml_training_jobs_algorithm", table_name="ml_training_jobs")
    op.drop_index("idx_ml_training_jobs_model_id", table_name="ml_training_jobs")
    op.drop_index("idx_ml_training_jobs_model_version_id", table_name="ml_training_jobs")
    op.drop_index("idx_ml_training_jobs_status", table_name="ml_training_jobs")
    op.drop_index("idx_ml_training_jobs_tenant_id", table_name="ml_training_jobs")
    op.create_index(
        op.f("ix_ml_training_jobs_algorithm"), "ml_training_jobs", ["algorithm"], unique=False
    )
    op.create_index(
        op.f("ix_ml_training_jobs_model_id"), "ml_training_jobs", ["model_id"], unique=False
    )
    op.create_index(
        op.f("ix_ml_training_jobs_model_version_id"),
        "ml_training_jobs",
        ["model_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ml_training_jobs_status"), "ml_training_jobs", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_ml_training_jobs_tenant_id"), "ml_training_jobs", ["tenant_id"], unique=False
    )
    op.alter_column(
        "model_artifacts",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "model_deployments",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "model_deployments",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index("idx_model_deployments_device", table_name="model_deployments")
    op.drop_index("idx_model_deployments_model_artifact_id", table_name="model_deployments")
    op.drop_index("idx_model_deployments_parent_deployment_id", table_name="model_deployments")
    op.drop_index("idx_model_deployments_status", table_name="model_deployments")
    op.drop_index("idx_model_deployments_target_device_id", table_name="model_deployments")
    op.drop_index("idx_model_deployments_target_group_id", table_name="model_deployments")
    op.drop_index("idx_model_deployments_target_type", table_name="model_deployments")
    op.create_index(
        op.f("ix_model_deployments_model_artifact_id"),
        "model_deployments",
        ["model_artifact_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_model_deployments_parent_deployment_id"),
        "model_deployments",
        ["parent_deployment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_model_deployments_status"), "model_deployments", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_model_deployments_target_device_id"),
        "model_deployments",
        ["target_device_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_model_deployments_target_group_id"),
        "model_deployments",
        ["target_group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_model_deployments_target_type"), "model_deployments", ["target_type"], unique=False
    )
    op.drop_index("idx_model_predictions_device_time", table_name="model_predictions")
    op.drop_index("idx_model_predictions_uid_time", table_name="model_predictions")
    op.drop_index("model_predictions_time_idx", table_name="model_predictions")
    op.alter_column(
        "ota_campaign_targets",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "ota_campaign_targets",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index("idx_ota_campaign_targets_device", table_name="ota_campaign_targets")
    op.alter_column(
        "ota_campaigns",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "ota_campaigns",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index("idx_ota_campaigns_status", table_name="ota_campaigns")
    op.alter_column(
        "ota_job_events",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "ota_jobs",
        "requested_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "ota_jobs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "ota_jobs",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index("idx_ota_jobs_campaign_id", table_name="ota_jobs")
    op.drop_index("idx_ota_jobs_device_status", table_name="ota_jobs")
    op.drop_index("idx_ota_jobs_tenant_created_at", table_name="ota_jobs")
    op.drop_index("idx_ota_jobs_tenant_id", table_name="ota_jobs")
    op.create_index(op.f("ix_ota_jobs_campaign_id"), "ota_jobs", ["campaign_id"], unique=False)
    op.create_index(op.f("ix_ota_jobs_tenant_id"), "ota_jobs", ["tenant_id"], unique=False)
    op.alter_column(
        "project_pages",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "project_pages",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "project_widgets",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "project_widgets",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "provisioning_sessions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "provisioning_sessions",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index("idx_provisioning_sessions_claim_code", table_name="provisioning_sessions")
    op.drop_index("idx_provisioning_sessions_device_id", table_name="provisioning_sessions")
    op.drop_index("idx_provisioning_sessions_tenant_id", table_name="provisioning_sessions")
    op.drop_index("idx_provisioning_sessions_tenant_status", table_name="provisioning_sessions")
    op.drop_constraint(
        "provisioning_sessions_claim_code_key", "provisioning_sessions", type_="unique"
    )
    op.create_index(
        op.f("ix_provisioning_sessions_claim_code"),
        "provisioning_sessions",
        ["claim_code"],
        unique=True,
    )
    op.create_index(
        op.f("ix_provisioning_sessions_device_id"),
        "provisioning_sessions",
        ["device_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_provisioning_sessions_tenant_id"),
        "provisioning_sessions",
        ["tenant_id"],
        unique=False,
    )
    op.alter_column(
        "service_plans",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "service_plans",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.add_column(
        "system_settings",
        sa.Column("public_site_config", sa.JSON(), server_default="{}", nullable=False),
    )
    op.alter_column(
        "system_settings",
        "allowed_release_channels",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text('\'["dev", "staging", "stable"]\'::jsonb'),
    )
    op.alter_column(
        "telemetry",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index("idx_telemetry_device_timestamp", table_name="telemetry")
    op.drop_index("idx_telemetry_device_ts_metric", table_name="telemetry")
    op.drop_index("idx_telemetry_metric_timestamp", table_name="telemetry")
    op.drop_index(
        "idx_telemetry_field_definitions_project_id", table_name="telemetry_field_definitions"
    )
    op.drop_index(
        "idx_telemetry_field_definitions_tenant_id", table_name="telemetry_field_definitions"
    )
    op.create_index(
        op.f("ix_telemetry_field_definitions_device_type"),
        "telemetry_field_definitions",
        ["device_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_telemetry_field_definitions_project_id"),
        "telemetry_field_definitions",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_telemetry_field_definitions_tenant_id"),
        "telemetry_field_definitions",
        ["tenant_id"],
        unique=False,
    )
    op.alter_column(
        "telemetry_schemas",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "telemetry_schemas",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "tenant_projects",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "tenant_projects",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "tenants",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "tenants",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "tenants",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "tenants",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "tenant_projects",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "tenant_projects",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "telemetry_schemas",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "telemetry_schemas",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        op.f("ix_telemetry_field_definitions_tenant_id"), table_name="telemetry_field_definitions"
    )
    op.drop_index(
        op.f("ix_telemetry_field_definitions_project_id"), table_name="telemetry_field_definitions"
    )
    op.drop_index(
        op.f("ix_telemetry_field_definitions_device_type"), table_name="telemetry_field_definitions"
    )
    op.create_index(
        "idx_telemetry_field_definitions_tenant_id",
        "telemetry_field_definitions",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "idx_telemetry_field_definitions_project_id",
        "telemetry_field_definitions",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        "idx_telemetry_metric_timestamp",
        "telemetry",
        ["metric_name", sa.text("timestamp DESC")],
        unique=False,
    )
    op.create_index(
        "idx_telemetry_device_ts_metric",
        "telemetry",
        ["device_id", sa.text("timestamp DESC"), "metric_name"],
        unique=False,
    )
    op.create_index(
        "idx_telemetry_device_timestamp",
        "telemetry",
        ["device_id", sa.text("timestamp DESC")],
        unique=False,
    )
    op.alter_column(
        "telemetry",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "system_settings",
        "allowed_release_channels",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text('\'["dev", "staging", "stable"]\'::jsonb'),
    )
    op.drop_column("system_settings", "public_site_config")
    op.alter_column(
        "service_plans",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "service_plans",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_provisioning_sessions_tenant_id"), table_name="provisioning_sessions")
    op.drop_index(op.f("ix_provisioning_sessions_device_id"), table_name="provisioning_sessions")
    op.drop_index(op.f("ix_provisioning_sessions_claim_code"), table_name="provisioning_sessions")
    op.create_unique_constraint(
        "provisioning_sessions_claim_code_key", "provisioning_sessions", ["claim_code"]
    )
    op.create_index(
        "idx_provisioning_sessions_tenant_status",
        "provisioning_sessions",
        ["tenant_id", "status"],
        unique=False,
    )
    op.create_index(
        "idx_provisioning_sessions_tenant_id", "provisioning_sessions", ["tenant_id"], unique=False
    )
    op.create_index(
        "idx_provisioning_sessions_device_id", "provisioning_sessions", ["device_id"], unique=False
    )
    op.create_index(
        "idx_provisioning_sessions_claim_code",
        "provisioning_sessions",
        ["claim_code"],
        unique=False,
    )
    op.alter_column(
        "provisioning_sessions",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "provisioning_sessions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "project_widgets",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "project_widgets",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "project_pages",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "project_pages",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_ota_jobs_tenant_id"), table_name="ota_jobs")
    op.drop_index(op.f("ix_ota_jobs_campaign_id"), table_name="ota_jobs")
    op.create_index("idx_ota_jobs_tenant_id", "ota_jobs", ["tenant_id"], unique=False)
    op.create_index(
        "idx_ota_jobs_tenant_created_at",
        "ota_jobs",
        ["tenant_id", sa.text("created_at DESC")],
        unique=False,
    )
    op.create_index("idx_ota_jobs_device_status", "ota_jobs", ["device_id", "status"], unique=False)
    op.create_index("idx_ota_jobs_campaign_id", "ota_jobs", ["campaign_id"], unique=False)
    op.alter_column(
        "ota_jobs",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "ota_jobs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "ota_jobs",
        "requested_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "ota_job_events",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.create_index("idx_ota_campaigns_status", "ota_campaigns", ["status"], unique=False)
    op.alter_column(
        "ota_campaigns",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "ota_campaigns",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        "idx_ota_campaign_targets_device", "ota_campaign_targets", ["device_id"], unique=False
    )
    op.alter_column(
        "ota_campaign_targets",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "ota_campaign_targets",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        "model_predictions_time_idx", "model_predictions", [sa.text("time DESC")], unique=False
    )
    op.create_index(
        "idx_model_predictions_uid_time",
        "model_predictions",
        ["device_uid", sa.text("time DESC")],
        unique=False,
    )
    op.create_index(
        "idx_model_predictions_device_time",
        "model_predictions",
        ["device_id", sa.text("time DESC")],
        unique=False,
    )
    op.drop_index(op.f("ix_model_deployments_target_type"), table_name="model_deployments")
    op.drop_index(op.f("ix_model_deployments_target_group_id"), table_name="model_deployments")
    op.drop_index(op.f("ix_model_deployments_target_device_id"), table_name="model_deployments")
    op.drop_index(op.f("ix_model_deployments_status"), table_name="model_deployments")
    op.drop_index(op.f("ix_model_deployments_parent_deployment_id"), table_name="model_deployments")
    op.drop_index(op.f("ix_model_deployments_model_artifact_id"), table_name="model_deployments")
    op.create_index(
        "idx_model_deployments_target_type", "model_deployments", ["target_type"], unique=False
    )
    op.create_index(
        "idx_model_deployments_target_group_id",
        "model_deployments",
        ["target_group_id"],
        unique=False,
    )
    op.create_index(
        "idx_model_deployments_target_device_id",
        "model_deployments",
        ["target_device_id"],
        unique=False,
    )
    op.create_index("idx_model_deployments_status", "model_deployments", ["status"], unique=False)
    op.create_index(
        "idx_model_deployments_parent_deployment_id",
        "model_deployments",
        ["parent_deployment_id"],
        unique=False,
    )
    op.create_index(
        "idx_model_deployments_model_artifact_id",
        "model_deployments",
        ["model_artifact_id"],
        unique=False,
    )
    op.create_index(
        "idx_model_deployments_device", "model_deployments", ["device_id"], unique=False
    )
    op.alter_column(
        "model_deployments",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "model_deployments",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "model_artifacts",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_ml_training_jobs_tenant_id"), table_name="ml_training_jobs")
    op.drop_index(op.f("ix_ml_training_jobs_status"), table_name="ml_training_jobs")
    op.drop_index(op.f("ix_ml_training_jobs_model_version_id"), table_name="ml_training_jobs")
    op.drop_index(op.f("ix_ml_training_jobs_model_id"), table_name="ml_training_jobs")
    op.drop_index(op.f("ix_ml_training_jobs_algorithm"), table_name="ml_training_jobs")
    op.create_index(
        "idx_ml_training_jobs_tenant_id", "ml_training_jobs", ["tenant_id"], unique=False
    )
    op.create_index("idx_ml_training_jobs_status", "ml_training_jobs", ["status"], unique=False)
    op.create_index(
        "idx_ml_training_jobs_model_version_id",
        "ml_training_jobs",
        ["model_version_id"],
        unique=False,
    )
    op.create_index("idx_ml_training_jobs_model_id", "ml_training_jobs", ["model_id"], unique=False)
    op.create_index(
        "idx_ml_training_jobs_algorithm", "ml_training_jobs", ["algorithm"], unique=False
    )
    op.alter_column(
        "ml_training_jobs",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "ml_training_jobs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_ml_models_tenant_id"), table_name="ml_models")
    op.drop_index(op.f("ix_ml_models_task_type"), table_name="ml_models")
    op.drop_index(op.f("ix_ml_models_status"), table_name="ml_models")
    op.drop_index(op.f("ix_ml_models_problem_type"), table_name="ml_models")
    op.create_index("idx_ml_models_tenant_id", "ml_models", ["tenant_id"], unique=False)
    op.create_index("idx_ml_models_task_type", "ml_models", ["task_type"], unique=False)
    op.create_index("idx_ml_models_status", "ml_models", ["status"], unique=False)
    op.create_index("idx_ml_models_problem_type", "ml_models", ["problem_type"], unique=False)
    op.alter_column(
        "ml_models",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "ml_models",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.create_foreign_key(
        "fk_ml_model_versions_training_job_id",
        "ml_model_versions",
        "ml_training_jobs",
        ["training_job_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_index(op.f("ix_ml_model_versions_tenant_id"), table_name="ml_model_versions")
    op.drop_index(op.f("ix_ml_model_versions_status"), table_name="ml_model_versions")
    op.drop_index(op.f("ix_ml_model_versions_stage"), table_name="ml_model_versions")
    op.drop_index(op.f("ix_ml_model_versions_is_active"), table_name="ml_model_versions")
    op.drop_index(op.f("ix_ml_model_versions_algorithm"), table_name="ml_model_versions")
    op.create_index(
        "idx_ml_model_versions_tenant_id", "ml_model_versions", ["tenant_id"], unique=False
    )
    op.create_index("idx_ml_model_versions_status", "ml_model_versions", ["status"], unique=False)
    op.create_index("idx_ml_model_versions_stage", "ml_model_versions", ["stage"], unique=False)
    op.create_index(
        "idx_ml_model_versions_is_active", "ml_model_versions", ["is_active"], unique=False
    )
    op.create_index(
        "idx_ml_model_versions_algorithm", "ml_model_versions", ["algorithm"], unique=False
    )
    op.alter_column(
        "ml_model_versions",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "ml_model_versions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_ml_inference_results_tenant_id"), table_name="ml_inference_results")
    op.drop_index(op.f("ix_ml_inference_results_runtime"), table_name="ml_inference_results")
    op.drop_index(op.f("ix_ml_inference_results_prediction"), table_name="ml_inference_results")
    op.drop_index(
        op.f("ix_ml_inference_results_model_version_id"), table_name="ml_inference_results"
    )
    op.drop_index(op.f("ix_ml_inference_results_model_id"), table_name="ml_inference_results")
    op.drop_index(op.f("ix_ml_inference_results_is_anomaly"), table_name="ml_inference_results")
    op.drop_index(op.f("ix_ml_inference_results_device_id"), table_name="ml_inference_results")
    op.drop_index(op.f("ix_ml_inference_results_created_at"), table_name="ml_inference_results")
    op.drop_index(op.f("ix_ml_inference_results_algorithm"), table_name="ml_inference_results")
    op.create_index(
        "idx_ml_inference_results_tenant_id", "ml_inference_results", ["tenant_id"], unique=False
    )
    op.create_index(
        "idx_ml_inference_results_runtime", "ml_inference_results", ["runtime"], unique=False
    )
    op.create_index(
        "idx_ml_inference_results_prediction", "ml_inference_results", ["prediction"], unique=False
    )
    op.create_index(
        "idx_ml_inference_results_model_version_id",
        "ml_inference_results",
        ["model_version_id"],
        unique=False,
    )
    op.create_index(
        "idx_ml_inference_results_model_id", "ml_inference_results", ["model_id"], unique=False
    )
    op.create_index(
        "idx_ml_inference_results_is_anomaly", "ml_inference_results", ["is_anomaly"], unique=False
    )
    op.create_index(
        "idx_ml_inference_results_device_id", "ml_inference_results", ["device_id"], unique=False
    )
    op.create_index(
        "idx_ml_inference_results_created_at", "ml_inference_results", ["created_at"], unique=False
    )
    op.create_index(
        "idx_ml_inference_results_algorithm", "ml_inference_results", ["algorithm"], unique=False
    )
    op.alter_column(
        "ml_inference_results",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_ml_anomaly_events_tenant_id"), table_name="ml_anomaly_events")
    op.drop_index(op.f("ix_ml_anomaly_events_status"), table_name="ml_anomaly_events")
    op.drop_index(op.f("ix_ml_anomaly_events_severity"), table_name="ml_anomaly_events")
    op.drop_index(op.f("ix_ml_anomaly_events_model_version_id"), table_name="ml_anomaly_events")
    op.drop_index(op.f("ix_ml_anomaly_events_inference_result_id"), table_name="ml_anomaly_events")
    op.drop_index(op.f("ix_ml_anomaly_events_device_id"), table_name="ml_anomaly_events")
    op.drop_index(op.f("ix_ml_anomaly_events_detected_at"), table_name="ml_anomaly_events")
    op.drop_index(op.f("ix_ml_anomaly_events_dedup_key"), table_name="ml_anomaly_events")
    op.create_index(
        "idx_ml_anomaly_events_tenant_id", "ml_anomaly_events", ["tenant_id"], unique=False
    )
    op.create_index("idx_ml_anomaly_events_status", "ml_anomaly_events", ["status"], unique=False)
    op.create_index(
        "idx_ml_anomaly_events_severity", "ml_anomaly_events", ["severity"], unique=False
    )
    op.create_index(
        "idx_ml_anomaly_events_model_version_id",
        "ml_anomaly_events",
        ["model_version_id"],
        unique=False,
    )
    op.create_index(
        "idx_ml_anomaly_events_inference_result_id",
        "ml_anomaly_events",
        ["inference_result_id"],
        unique=False,
    )
    op.create_index(
        "idx_ml_anomaly_events_device_id", "ml_anomaly_events", ["device_id"], unique=False
    )
    op.create_index(
        "idx_ml_anomaly_events_detected_at", "ml_anomaly_events", ["detected_at"], unique=False
    )
    op.create_index(
        "idx_ml_anomaly_events_dedup_key", "ml_anomaly_events", ["dedup_key"], unique=False
    )
    op.alter_column(
        "ml_anomaly_events",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "ml_anomaly_events",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "ml_anomaly_events",
        "detected_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_intelligence_profiles_profile_type"), table_name="intelligence_profiles")
    op.drop_index(op.f("ix_intelligence_profiles_is_active"), table_name="intelligence_profiles")
    op.create_index(
        "idx_intelligence_profiles_type", "intelligence_profiles", ["profile_type"], unique=False
    )
    op.create_index(
        "idx_intelligence_profiles_active", "intelligence_profiles", ["is_active"], unique=False
    )
    op.alter_column(
        "intelligence_profiles",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "intelligence_profiles",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        "idx_health_scores_uid_time",
        "health_scores",
        ["device_uid", sa.text("time DESC")],
        unique=False,
    )
    op.create_index(
        "idx_health_scores_device_time",
        "health_scores",
        ["device_id", sa.text("time DESC")],
        unique=False,
    )
    op.create_index("health_scores_time_idx", "health_scores", [sa.text("time DESC")], unique=False)
    op.create_index(
        "uq_firmware_version_type_tenant",
        "firmware_versions",
        ["version", "target_device_type", "uploaded_by_tenant_id"],
        unique=True,
        postgresql_where="(uploaded_by_tenant_id IS NOT NULL)",
    )
    op.create_index(
        "uq_firmware_version_type_global",
        "firmware_versions",
        ["version", "target_device_type"],
        unique=True,
        postgresql_where="(uploaded_by_tenant_id IS NULL)",
    )
    op.create_index(
        "uq_firmware_tenant_version",
        "firmware_versions",
        ["uploaded_by_tenant_id", "target_device_type", "version"],
        unique=True,
        postgresql_where="(uploaded_by_tenant_id IS NOT NULL)",
    )
    op.create_index(
        "uq_firmware_global_version",
        "firmware_versions",
        ["target_device_type", "version"],
        unique=True,
        postgresql_where="(uploaded_by_tenant_id IS NULL)",
    )
    op.create_index(
        "idx_firmware_tenant_type",
        "firmware_versions",
        ["uploaded_by_tenant_id", "target_device_type"],
        unique=False,
        postgresql_where="(uploaded_by_tenant_id IS NOT NULL)",
    )
    op.alter_column(
        "firmware_versions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        "idx_firmware_profiles_device_type", "firmware_profiles", ["device_type_id"], unique=False
    )
    op.alter_column(
        "firmware_profiles",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "firmware_profiles",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_devices_device_type_id"), table_name="devices")
    op.create_index("idx_devices_status", "devices", ["status"], unique=False)
    op.create_index(
        "idx_devices_last_seen_at", "devices", [sa.text("last_seen_at DESC")], unique=False
    )
    op.create_index("idx_devices_hardware_model", "devices", ["hardware_model"], unique=False)
    op.create_index("idx_devices_device_type_id", "devices", ["device_type_id"], unique=False)
    op.alter_column(
        "devices",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "devices",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_device_types_key"), table_name="device_types")
    op.create_index("idx_device_types_key", "device_types", ["key"], unique=False)
    op.create_unique_constraint("device_types_key_key", "device_types", ["key"])
    op.alter_column(
        "device_types",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "device_types",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_table_comment(
        "device_status_events",
        existing_comment="Time-series device status transitions (may be hypertable)",
        schema=None,
    )
    op.create_index(
        "idx_device_status_events_uid_time",
        "device_status_events",
        ["device_uid", sa.text("time DESC")],
        unique=False,
    )
    op.create_index(
        "idx_device_status_events_device_time",
        "device_status_events",
        ["device_id", sa.text("time DESC")],
        unique=False,
    )
    op.create_index(
        "device_status_events_time_idx",
        "device_status_events",
        [sa.text("time DESC")],
        unique=False,
    )
    op.alter_column(
        "device_platforms",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "device_platforms",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "device_models",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "device_models",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_table_comment(
        "device_health",
        existing_comment="Time-series device health metrics (may be hypertable)",
        schema=None,
    )
    op.create_index(
        "idx_device_health_uid_time",
        "device_health",
        ["device_uid", sa.text("time DESC")],
        unique=False,
    )
    op.create_index(
        "idx_device_health_device_time",
        "device_health",
        ["device_id", sa.text("time DESC")],
        unique=False,
    )
    op.create_index("device_health_time_idx", "device_health", [sa.text("time DESC")], unique=False)
    op.alter_column(
        "device_health",
        "uptime_ms",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=True,
    )
    op.drop_index("idx_device_groups_status", table_name="device_groups")
    op.create_index(
        "idx_device_groups_tenant_created_at",
        "device_groups",
        ["tenant_id", sa.text("created_at DESC")],
        unique=False,
    )
    op.alter_column(
        "device_groups",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "device_groups",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "device_group_members",
        "added_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        "idx_device_credentials_type", "device_credentials", ["credential_type"], unique=False
    )
    op.alter_column(
        "device_credentials",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "device_capabilities",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "device_capabilities",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_command_templates_tenant_id"), table_name="command_templates")
    op.create_index(
        "idx_command_templates_tenant_id", "command_templates", ["tenant_id"], unique=False
    )
    op.alter_column(
        "command_templates",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "command_templates",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "command_templates",
        "is_system",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.drop_index(op.f("ix_command_targets_dispatch_id"), table_name="command_targets")
    op.drop_index(op.f("ix_command_targets_device_id"), table_name="command_targets")
    op.create_unique_constraint(
        "uq_command_targets_dispatch_device", "command_targets", ["dispatch_id", "device_id"]
    )
    op.create_index(
        "idx_command_targets_dispatch_id", "command_targets", ["dispatch_id"], unique=False
    )
    op.create_index("idx_command_targets_device_id", "command_targets", ["device_id"], unique=False)
    op.alter_column(
        "command_targets",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "command_targets",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_command_dispatches_tenant_id"), table_name="command_dispatches")
    op.create_index(
        "idx_command_dispatches_tenant_id", "command_dispatches", ["tenant_id"], unique=False
    )
    op.create_index(
        "idx_command_dispatches_tenant_created",
        "command_dispatches",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_index("idx_command_dispatches_status", "command_dispatches", ["status"], unique=False)
    op.alter_column(
        "command_dispatches",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "command_dispatches",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "command_dispatches",
        "max_retries",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("3"),
    )
    op.alter_column(
        "command_dispatches",
        "retry_count",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "capability_templates",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "capability_templates",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_automation_rules_tenant_id"), table_name="automation_rules")
    op.drop_index(op.f("ix_automation_rules_project_id"), table_name="automation_rules")
    op.create_index(
        "idx_automation_rules_tenant_id", "automation_rules", ["tenant_id"], unique=False
    )
    op.create_index(
        "idx_automation_rules_project_id", "automation_rules", ["project_id"], unique=False
    )
    op.drop_index(
        op.f("ix_automation_rule_executions_tenant_id"), table_name="automation_rule_executions"
    )
    op.drop_index(
        op.f("ix_automation_rule_executions_rule_id"), table_name="automation_rule_executions"
    )
    op.drop_index(
        op.f("ix_automation_rule_executions_device_id"), table_name="automation_rule_executions"
    )
    op.create_index(
        "idx_automation_rule_executions_tenant_id",
        "automation_rule_executions",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "idx_automation_rule_executions_rule_id",
        "automation_rule_executions",
        ["rule_id"],
        unique=False,
    )
    op.create_index(
        "idx_automation_rule_executions_device_id",
        "automation_rule_executions",
        ["device_id"],
        unique=False,
    )
    op.create_index(
        "idx_audit_logs_tenant_created_at",
        "audit_logs",
        ["tenant_id", sa.text("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "idx_audit_logs_ip_address",
        "audit_logs",
        ["ip_address"],
        unique=False,
        postgresql_where="(ip_address IS NOT NULL)",
    )
    op.alter_column(
        "audit_logs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "api_doc_overrides",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "api_doc_overrides",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "anomaly_events",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        "idx_alerts_tenant_created_at",
        "alerts",
        ["tenant_id", sa.text("created_at DESC")],
        unique=False,
    )
    op.create_index("idx_alerts_status_severity", "alerts", ["status", "severity"], unique=False)
    op.create_index("idx_alerts_source_code", "alerts", ["source", "code"], unique=False)
    op.create_index(
        "idx_alerts_device_created_at",
        "alerts",
        ["device_id", sa.text("created_at DESC")],
        unique=False,
    )
    op.alter_column(
        "alerts",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "alerts",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "alerts",
        "last_seen_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "alerts",
        "first_seen_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###
