"""add_datastream_compatibility

Revision ID: a910c513841a
Revises: 0011
Create Date: 2026-07-11 10:46:34.907040
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a910c513841a'
down_revision: Union[str, None] = '0011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datastream_template_compatibilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('datastream_id', sa.Uuid(), nullable=False),
    sa.Column('device_model_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['datastream_id'], ['tenant_datastreams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_model_id'], ['device_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('datastream_id', 'device_model_id', name='uq_datastream_model_compatibility')
    )
    op.create_index(op.f('ix_datastream_template_compatibilities_datastream_id'), 'datastream_template_compatibilities', ['datastream_id'], unique=False)
    op.create_index(op.f('ix_datastream_template_compatibilities_device_model_id'), 'datastream_template_compatibilities', ['device_model_id'], unique=False)
    op.drop_index(op.f('idx_devices_project_id'), table_name='devices')
    op.create_index(op.f('ix_devices_project_id'), 'devices', ['project_id'], unique=False)
    op.drop_index(op.f('idx_ota_campaigns_project_id'), table_name='ota_campaigns')
    op.create_index(op.f('ix_ota_campaigns_project_id'), 'ota_campaigns', ['project_id'], unique=False)
    op.drop_constraint(op.f('uq_project_firmware_ref'), 'project_firmware_references', type_='unique')
    op.add_column('tenant_datastreams', sa.Column('is_custom', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('tenant_datastreams', sa.Column('status', sa.String(length=32), nullable=False, server_default='active'))
    op.drop_index(op.f('idx_project_datastreams_pin'), table_name='tenant_datastreams')
    op.drop_index(op.f('idx_tenant_datastreams_project_id'), table_name='tenant_datastreams')
    op.drop_index(op.f('idx_tenant_datastreams_tenant_id'), table_name='tenant_datastreams')
    op.create_index(op.f('ix_tenant_datastreams_project_id'), 'tenant_datastreams', ['project_id'], unique=False)
    op.drop_constraint(op.f('uq_tenant_firmware_ver'), 'tenant_firmwares', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_tenant_firmware_ver'), 'tenant_firmwares', ['tenant_id', 'hardware_model', 'version'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_tenant_datastreams_project_id'), table_name='tenant_datastreams')
    op.create_index(op.f('idx_tenant_datastreams_tenant_id'), 'tenant_datastreams', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_tenant_datastreams_project_id'), 'tenant_datastreams', ['project_id'], unique=False)
    op.create_index(op.f('idx_project_datastreams_pin'), 'tenant_datastreams', ['project_id', 'pin'], unique=False)
    op.drop_column('tenant_datastreams', 'status')
    op.drop_column('tenant_datastreams', 'is_custom')
    op.create_unique_constraint(op.f('uq_project_firmware_ref'), 'project_firmware_references', ['project_id', 'firmware_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_ota_campaigns_project_id'), table_name='ota_campaigns')
    op.create_index(op.f('idx_ota_campaigns_project_id'), 'ota_campaigns', ['project_id'], unique=False)
    op.drop_index(op.f('ix_devices_project_id'), table_name='devices')
    op.create_index(op.f('idx_devices_project_id'), 'devices', ['project_id'], unique=False)
    op.drop_index(op.f('ix_datastream_template_compatibilities_device_model_id'), table_name='datastream_template_compatibilities')
    op.drop_index(op.f('ix_datastream_template_compatibilities_datastream_id'), table_name='datastream_template_compatibilities')
    op.drop_table('datastream_template_compatibilities')
    # ### end Alembic commands ###
